from .cross_entropy import LabelSmoothingCrossEntropy, SoftTargetCrossEntropy, BiasedLossCrossEntropy
from .jsd import JsdCrossEntropy
from .asymmetric_loss import AsymmetricLossMultiLabel, AsymmetricLossSingleLabel